# Generated by Django 4.2.9 on 2024-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='https://avatars.githubusercontent.com/u/44887498?v=4', null=True, upload_to='static/', verbose_name='avatar'),
        ),
    ]
