# Generated by Django 4.2.9 on 2024-01-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuid',
            new_name='id',
        ),
    ]
